In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [3]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [4]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [5]:
# Question 1 - Answer is Version 2.3.1
pd.__version__

'2.3.1'

In [6]:
# Question 2 - Answer is 9704
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [7]:
# Question 3 - Answer is 2
df.value_counts('fuel_type')


fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [8]:
# Question 4 - Answer is 4
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [9]:
# Question 5 - Answer is 23.75
df[df['origin'] == 'Asia'].max()


engine_displacement                  370
num_cylinders                       11.0
horsepower                         245.0
vehicle_weight               4661.144932
acceleration                        22.7
model_year                          2023
origin                              Asia
fuel_type                       Gasoline
drivetrain             Front-wheel drive
num_doors                            4.0
fuel_efficiency_mpg            23.759123
dtype: object

In [ ]:
# Question 6 - Median Value of HP is 149
df['horsepower'].median()

np.float64(149.0)

In [ ]:
# Question 6 - Mode or Frequency of Horspower is 152
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [12]:
# Question 6 - Filling missing values with 159 in the horsepower column
df['horsepower'] = df['horsepower'].fillna(159)

In [13]:
# Question 6 - checking that horsepower no longer has missing values
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [ ]:
# Question 6 - New Median is now 152 an increase from 149 before filling missing values with 159
df['horsepower'].median()

np.float64(152.0)

# Q7. Sum of weights
* Select all the cars from Asia
* Select only columns vehicle_weight and model_year
* Select the first 7 values
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
* Invert XTX.
* Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
* What's the sum of all the elements of the result?

In [62]:
# Question 7 - Filtering to Asia vehicles only and returning the vehicle_weight & model_year columns only
a = df[df['origin'] == 'Asia']
a = df[['vehicle_weight', 'model_year']]
a = a.iloc[:7]
a

vehicle_weight  model_year
0     3413.433759        2003
1     3149.664934        2007
2     3079.038997        2018
3     2542.392402        2009
4     3460.870990        2009
5     2484.883986        2008
6     3006.542287        2012

In [63]:
# Question 7 - return array x and transpose of x
X = np.array(a)
Xt = X.T # Transpose of X

print(X)
print("X Shape:", X.shape)
print(Xt)
print("Xt Shape:",Xt.shape)


[[3413.43375861 2003.        ]
 [3149.66493422 2007.        ]
 [3079.03899737 2018.        ]
 [2542.39240183 2009.        ]
 [3460.87098999 2009.        ]
 [2484.88398604 2008.        ]
 [3006.54228722 2012.        ]]
X Shape: (7, 2)
[[3413.43375861 3149.66493422 3079.03899737 2542.39240183 3460.87098999
  2484.88398604 3006.54228722]
 [2003.         2007.         2018.         2009.         2009.
  2008.         2012.        ]]
Xt Shape: (2, 7)


In [64]:
# Question 7 - Matrix-Matrix Multiplication of X & XT
XTX = Xt.dot(X)
print(XTX)
print("XTX Shape:", XTX.shape)

[[64707732.45267162 42471352.31816065]
 [42471352.31816065 28264752.        ]]
XTX Shape: (2, 2)


In [65]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print(y)
print("y Shape:",y.shape)

[1100 1300  800  900 1000 1100 1200]
y Shape: (7,)


In [66]:
# The formula is w = (XTX_inv * Xt) * y.
# Matrix multiplication is associative, meaning (A * B) * C = A * (B * C).
# Or (XTX_inv * Xt) * y = XTX_inv * (Xt * y)

Xty = np.dot(Xt,y) # Multiply Xt * y
XTX_inv = np.linalg.inv(XTX) # Get the inverse of XTX
print(Xty)
print("Xty Shape",Xty.shape)
print(XTX_inv)
print("XTX_inv Shape:",XTX_inv.shape)
print()
print("X Shape:", X.shape)
print("Xt Shape:",Xt.shape)
print("XTX Shape:", XTX.shape)
print("y Shape:",y.shape)


[22402820.02778277 14867100.        ]
Xty Shape (2,)
[[ 1.12464107e-06 -1.68991495e-06]
 [-1.68991495e-06  2.57468996e-06]]
XTX_inv Shape: (2, 2)

X Shape: (7, 2)
Xt Shape: (2, 7)
XTX Shape: (2, 2)
y Shape: (7,)


In [67]:
#Question 7 - Calculate the weights and the sum of the weights - Answer is 0.49 but this does not exist in the answer set so 0.51 is the closest
w = np.dot(XTX_inv,Xty)
print("Weights:",w)
print()

sum_w = w.sum().round(2)
print("Sum of Weights:", sum_w)

Weights: [0.07099685 0.41931263]

Sum of Weights: 0.49
