In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [3]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [4]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [5]:
# Question 1 - Answer is Version 2.3.1

In [6]:
# Question 2 - Answer is 9704
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [7]:
# Question 3 - Answer is 2
df.value_counts('fuel_type')


fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [8]:
# Question 4 - Answer is 4
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [9]:
# Question 5 - Answer is 25.96 but HW does not have this as an answer for this question
df.max()

engine_displacement                  380
num_cylinders                       13.0
horsepower                         271.0
vehicle_weight               4739.077089
acceleration                        24.3
model_year                          2023
origin                               USA
fuel_type                       Gasoline
drivetrain             Front-wheel drive
num_doors                            4.0
fuel_efficiency_mpg            25.967222
dtype: object

In [10]:
# Question 6 - Median Value of HP is 149
df.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  8996.000000     9704.000000   
mean            199.708368       3.962481   149.657292     3001.280993   
std              49.455319       1.999323    29.879555      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   130.000000     2666.248985   
50%             200.000000       4.000000   149.000000     2993.226296   
75%             230.000000       5.000000   170.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

In [11]:
# Question 6 - Mode or Frequency of Horspower is 159
df.mode(numeric_only=True)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                   190.0            4.0       152.0      952.681761   
1                     NaN            NaN         NaN     1066.328301   
2                     NaN            NaN         NaN     1223.298226   
3                     NaN            NaN         NaN     1314.839625   
4                     NaN            NaN         NaN     1336.444231   
...                   ...            ...         ...             ...   
9699                  NaN            NaN         NaN     4610.973229   
9700                  NaN            NaN         NaN     4643.568672   
9701                  NaN            NaN         NaN     4661.144932   
9702                  NaN            NaN         NaN     4726.977269   
9703                  NaN            NaN         NaN     4739.077089   

      acceleration  model_year  num_doors  fuel_efficiency_mpg  
0             15.6      2003.0        0.0             6.200971  
1              NaN         NaN        NaN             6.676475  
2              NaN         NaN        NaN             6.695483  
3              NaN         NaN        NaN             6.762991  
4              NaN         NaN        NaN             6.805975  
...            ...         ...        ...                  ...  
9699           NaN         NaN        NaN            23.369176  
9700           NaN         NaN        NaN            23.556075  
9701           NaN         NaN        NaN            23.759123  
9702           NaN         NaN        NaN            24.971452  
9703           NaN         NaN        NaN            25.967222  

[9704 rows x 8 columns]

In [12]:
# Question 6 - Filling missing values with 159 in the horsepower column
df['horsepower'] = df['horsepower'].fillna(159)

In [13]:
# Question 6 - checking that horsepower no longer has missing values
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [14]:
# Question 6 - New Median is now 159 and it increased
df.mode(numeric_only=True)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                   190.0            4.0       159.0      952.681761   
1                     NaN            NaN         NaN     1066.328301   
2                     NaN            NaN         NaN     1223.298226   
3                     NaN            NaN         NaN     1314.839625   
4                     NaN            NaN         NaN     1336.444231   
...                   ...            ...         ...             ...   
9699                  NaN            NaN         NaN     4610.973229   
9700                  NaN            NaN         NaN     4643.568672   
9701                  NaN            NaN         NaN     4661.144932   
9702                  NaN            NaN         NaN     4726.977269   
9703                  NaN            NaN         NaN     4739.077089   

      acceleration  model_year  num_doors  fuel_efficiency_mpg  
0             15.6      2003.0        0.0             6.200971  
1              NaN         NaN        NaN             6.676475  
2              NaN         NaN        NaN             6.695483  
3              NaN         NaN        NaN             6.762991  
4              NaN         NaN        NaN             6.805975  
...            ...         ...        ...                  ...  
9699           NaN         NaN        NaN            23.369176  
9700           NaN         NaN        NaN            23.556075  
9701           NaN         NaN        NaN            23.759123  
9702           NaN         NaN        NaN            24.971452  
9703           NaN         NaN        NaN            25.967222  

[9704 rows x 8 columns]

Q7. Sum of weights
Select all the cars from Asia
Select only columns vehicle_weight and model_year
Select the first 7 values
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?

In [15]:
# Question 7 - Filtering to Asia vehicles only and returning the vehicle_weight & model_year columns only
a = df[df['origin'] == 'Asia']
a = df[['vehicle_weight', 'model_year']]
a = a.iloc[:7]
a

vehicle_weight  model_year
0     3413.433759        2003
1     3149.664934        2007
2     3079.038997        2018
3     2542.392402        2009
4     3460.870990        2009
5     2484.883986        2008
6     3006.542287        2012

In [16]:
# Question 7 - return array x and transpose of x
X = np.array([a.vehicle_weight,a.model_year])
XT = X.T

print(X)
print(XT)


[[3413.43375861 3149.66493422 3079.03899737 2542.39240183 3460.87098999
  2484.88398604 3006.54228722]
 [2003.         2007.         2018.         2009.         2009.
  2008.         2012.        ]]
[[3413.43375861 2003.        ]
 [3149.66493422 2007.        ]
 [3079.03899737 2018.        ]
 [2542.39240183 2009.        ]
 [3460.87098999 2009.        ]
 [2484.88398604 2008.        ]
 [3006.54228722 2012.        ]]


In [17]:
# Question 7 - Matri-Matrix Multiplication of X & XT
XTX = X.dot(XT)
XTX

array([[64707732.45267162, 42471352.31816065],
       [42471352.31816065, 28264752.        ]])

In [18]:
# Question 7 - Invert XTX
XTX = np.flip(XTX)
XTX

array([[28264752.        , 42471352.31816065],
       [42471352.31816065, 64707732.45267162]])

In [19]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [20]:
XTX.dot(XT)

ValueError: shapes (2,2) and (7,2) not aligned: 2 (dim 1) != 7 (dim 0)